server:
  port: 8090
# 指定服务命名
spring:
  application:
    name: turbine
# 指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
# 指定聚合的项目
turbine:
  aggregator:
    cluster-config: default
  app-config: consumer
  clusterNameExpression: new String("default")
  instanceUrlSuffix:
    default: actuator/hystrix.stream


